management:
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    env:
      enabled: true
  application:
    name: spring-content
    description: A content with articles about the spring framework.
    author: Efhem
    version: 0.0.1

spring:
  profiles:
    active: dev
